{% set version = "1.4.1.post-1" %}
{% set sha256 = "033982873936542a2fac7c74242bc1f80411611079b1a998d7f66f8a3c9945dc" %}

package:
    name: falcon
    # version: {{ version }}
    # Conda does not allow a dash in the version
    version: 1.4.1.post1

source:
    fn: falcon-{{ version }}.tar.gz
    url: https://github.com/falconry/falcon/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 1000
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    entry_points:
      - falcon-bench = falcon.cmd.bench:main
      - falcon-print-routes = falcon.cmd.print_routes:main

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - python
        - pip
        - setuptools
        - cython
    run:
        - python
        - six >=1.4.0
        - python-mimeparse >=1.5.2

test:
    imports:
        - falcon
        - falcon.cmd
        - falcon.media
        - falcon.routing
        - falcon.testing
        - falcon.util

    commands:
        - falcon-bench -h
        - falcon-print-routes -h

about:
    home: http://falconframework.org
    license: Apache-2.0
    license_file: LICENSE
    summary: 'An unladen web framework for building APIs and app backends.'
    description: |
        Falcon is a high-performance Python framework for building cloud APIs. It
        encourages the REST architectural style, and tries to do as little as
        possible while remaining highly effective.
    doc_url: http://falcon.readthedocs.io/en/stable/
    dev_url: https://github.com/falconry/falcon/

extra:
    recipe-maintainers:
        - daf
        - synapticarbors
        - carlodri
