{% set version = "1.4.1" %}
{% set sha256 = "1c3185a131977bcb9f6d53a5f90a2462f040cd16152aaefd2f70e0e43979209a" %}

package:
    name: falcon
    version: {{ version }}

source:
    fn: falcon-{{ version }}.tar.gz
    url: https://github.com/falconry/falcon/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt
    entry_points:
      - falcon-bench = falcon.cmd.bench:main
      - falcon-print-routes = falcon.cmd.print_routes:main

requirements:
    build:
        - python
        - setuptools
        - cython
    run:
        - python
        - six >=1.4.0
        - python-mimeparse >=1.5.2

test:
    imports:
        - falcon
        - falcon.cmd
        - falcon.media
        - falcon.routing
        - falcon.testing
        - falcon.util

    commands:
        - falcon-bench -h
        - falcon-print-routes -h

about:
    home: http://falconframework.org
    license: Apache-2.0
    license_file: LICENSE
    summary: 'An unladen web framework for building APIs and app backends.'
    description: |
        Falcon is a high-performance Python framework for building cloud APIs. It
        encourages the REST architectural style, and tries to do as little as
        possible while remaining highly effective.
    doc_url: http://falcon.readthedocs.io/en/stable/
    dev_url: https://github.com/falconry/falcon/

extra:
    recipe-maintainers:
        - daf
        - synapticarbors
