travis:
  secure:
    BINSTAR_TOKEN: WZnPkEuugOuoRAlrIflSiyKDzVYZMLGkTQbAv5fFscgNWAl6eSEzcMZT1luAJBlkfKJJthC/C+2J5irdJ4gkadI9qX1Xd70S2eJnRCUj5vZdGAeFfQHpOdzbEJJPkRyWJiRUfzF/SFd7c7Ns9m9bFQ15lt/dPIwE+hM1NBGFhq8pvItjOgWG4AuC0ZD7n7X/fbyD0WTWP0rTaC1fQzKfSkCoHHkqdrfq5WhHDTjnnp2bDXckyPZzjh8lvytaTuYccw2NnB6emgqjbcfbCB7yZCYzPI3hTWZnActi5O1jvNx/DZs6VqWR6gZk4X5zp+Z1R2fhy1ADKzw/tyNPeWj3cDUapGeXHEldItV356ZgKolyxEre89UjZhcsErS5IKhGAzXOCmvJXAtBUWEaaDY3ueS/tHtFoxtLXb3LWr3et+oG6Y82Ki99QmBM54Aun+XrXp0ZBVbEYWXtR/EBMK011j1JjSTe0DU4FhcKVygPpF+P+MFFPcFuAD0e5HdiEP3Hnlt875RTnO/eQgUZSYzT56Ag6fdUQhnKSx08Cqma42zmzivT7vxLge7+vXEZljsV+POiSt3zFzhbWkjnG4WkGcrepl18QGKKMpz4ESgMwfgR+aKMl9V73LLSTJ3RsvCOKSF+D98nS+3H8JvI/Ooh5pzxMdMs4ouHGzFeREemeAU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
