travis:
  secure:
    BINSTAR_TOKEN: LWDHxUkw7lCGi1vzTbtWSPIbmjvKPbcw4rClqsuXNtosYi/6y5QCNEqM8YPSXA9j8joioUvGFDbfFWUEOMFVJwrIuVfc6a0nor4giXieh4GwV4Chsw3+vO7mLe3poMhtdDdAQ+gKb4LgpY5CeCc/nIANw+tZZ4tigXbhAa55YWY77tp9x1XPTYghZszHx6a4DOo5LwXKaVdADLprg6ss4dLHdZGFHDK9bNQg59pNdDrXSZ/ambyzq53mbZNZquQJs/7qibbFDi0iQvTck/iR0V62C3bnyLhnkVY5y4GePKoGU3r6a5C/GGDcMISXx+WI31AcvfYFPoKy/iqHikn7cfAOeBpfMvz75HRYw08SFnrvZsKIQ/jO2SUPlXflmngIcJk8BmNUCFC6tVZqXcnX1HoFf76lFjTweP9RwgvcJNRk2UMSkXmCPhYjS2+BLeKjojNhfzpT2Vx+joOymiwM5KnxcOV1sB5UkGbD5h0OuvB8m7MO4IJYnB7ImLkgYZ2WanneP/FCLwupwthjPwQWYfbSGrG8LIZvf+6DxH3KEGZOuF+FuGIj/qd+Pmagd44rtVRUX3uUSmkYuDuoxASnh/aSW4oUWZv5yyKrPYEY+0PdxRYqTMseglWF+NaFRy5MhJn1ZZ8QHjt7h/Kwd7ErlzjC6qyaawtHddc77S0dwPM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
